#!/bin/bash
# Quick Commit Guide - Copy & Paste Safe Commands

echo "🚀 C3OPS Infrastructure - GitHub Commit Guide"
echo ""
echo "Step 1: Verify Security"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Run this security check:"
echo ""
echo "  cd /Users/ck/c3ops-repos/c3ops-core-infra"
echo "  bash pre-commit-security-check.sh"
echo ""
echo ""
echo "Step 2: Review Changes"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "See what will be committed:"
echo ""
echo "  git status"
echo "  git diff --staged | head -100"
echo ""
echo ""
echo "Step 3: Commit Code"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Stage and commit everything:"
echo ""
echo "  git add ."
echo ""
echo "  git commit -m 'Deploy C3OPS infrastructure with React app"
echo ""
echo "  - Infrastructure: Terraform-managed AWS resources"
echo "  - Application: Vite React TypeScript app"
echo "  - Region: ap-south-2"
echo "  - State: S3 backend with DynamoDB locks'"
echo ""
echo ""
echo "Step 4: Push to GitHub"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Push your changes:"
echo ""
echo "  git push origin main"
echo ""
echo ""
echo "✅ Done! Your code is now on GitHub"
echo ""
